/**
 * Configuration Template for TopCinema
 *
 * For local development:
 * Copy this file to `config.js` and set your proxy URL:
 *   cp shared/config.example.js shared/config.js
 *
 * In production (GitHub Pages):
 * `config.js` is automatically generated by GitHub Actions using the `PROXY_URL` repository secret.
 */
export const base_url = '';

